# Generated by Django 4.0.1 on 2022-03-14 21:41

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_people_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='creator',
        ),
        migrations.AddField(
            model_name='people',
            name='home',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='people',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
