# Generated by Django 4.0.1 on 2022-04-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_remove_people_creator_people_home_people_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
    ]
