# Generated by Django 4.0.1 on 2022-04-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='address',
        ),
        migrations.AddField(
            model_name='properties',
            name='address1',
            field=models.CharField(default='n/a', max_length=255),
        ),
        migrations.AddField(
            model_name='properties',
            name='address2',
            field=models.CharField(default='n/a', max_length=255),
        ),
        migrations.AddField(
            model_name='properties',
            name='city_state_zip',
            field=models.CharField(default='Missoula, MT 59801', max_length=255),
        ),
    ]
