# Generated by Django 4.0.1 on 2022-04-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_properties_address_properties_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='address2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
