# Generated by Django 4.0.1 on 2022-04-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_properties_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='city_state_zip',
        ),
        migrations.AddField(
            model_name='properties',
            name='postalcode',
            field=models.CharField(default='59801', max_length=255),
        ),
    ]
