# Generated by Django 4.0.1 on 2022-05-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_people_options'),
        ('properties', '0004_remove_properties_city_state_zip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='owners',
            field=models.ManyToManyField(to='people.People'),
        ),
    ]
