# Generated by Django 4.0.1 on 2022-01-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_people_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='email',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
    ]
